[package]
name = "lib_import"
version = "0.1.0"
authors = ["Гужва Никита <n.guzhva@cognitivepilot.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
cmake = "0.1"

[dependencies]
libc = "0.2"
